name: Push Arch User Repository (AUR) Package

on:
    workflow_dispatch:
    release:
        types: [published, prereleased]

concurrency:
    group: aur-publish
    cancel-in-progress: false

jobs:
    aur-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Update Package Version
              run: |
                  TAG=$(gh release list --limit 1 --json tagName --jq '.[0].tagName')
                  sed -i "s/pkgver=.*/pkgver=$TAG/" ./pkgbuild/PKGBUILD

            - name: Publish AUR package
              uses: KSXGitHub/github-actions-deploy-aur@master
              with:
                  pkgname: millennium
                  pkgbuild: ./pkgbuild/PKGBUILD
                  assets: ./pkgbuild/millennium.install
                  commit_username: GitHub Actions
                  commit_email: github-actions@github.com
                  ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
                  commit_message: Update AUR package
                  ssh_keyscan_types: rsa,ecdsa,ed25519
